import { test, expect } from 'playwright/test'
const api='http://localhost:3002/api'
test.use({extraHTTPHeaders:{'X-Forwarded-For':'10.30.0.79'}})
test('admin creates a custom brigade role; employee sees only allowed sections and API denies writes',async({page,request},info)=>{
  const suffix=`${Date.now()}-${info.project.name}`,name=`Мастер ИТР ${suffix}`,username=`access-${suffix}`,password='access-browser-password'
  const admin=await request.post(`${api}/auth/login`,{data:{username:process.env.ADMIN_USERNAME||'e2e-admin',password:process.env.ADMIN_PASSWORD||'e2e-admin-password'}})
  expect(admin.ok()).toBeTruthy();const headers={Authorization:`Bearer ${(await admin.json()).accessToken}`}
  const b=await request.post(`${api}/brigades`,{headers,data:{name:`ИТР ${suffix}`}});expect(b.ok()).toBeTruthy();const brigade=await b.json()
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  await page.goto('/admin/access-roles')
  await page.getByLabel('Логин',{exact:true}).fill(process.env.ADMIN_USERNAME||'e2e-admin')
  await page.getByLabel('Пароль',{exact:true}).fill(process.env.ADMIN_PASSWORD||'e2e-admin-password')
  await page.getByRole('button',{name:'Войти',exact:true}).click()
  const form=page.getByRole('form',{name:'Настройка роли'})
  await form.getByLabel('Название роли',{exact:true}).fill(name)
  await form.getByLabel('Тип доступа',{exact:true}).selectOption('BRIGADIER')
  await form.getByLabel('Можно привязывать к бригаде',{exact:true}).check()
  await form.getByRole('group',{name:'Видимые разделы'}).getByLabel('Виды работ',{exact:true}).check()
  const detail=form.locator('details').filter({has:page.locator('summary',{hasText:/^Виды работ/})})
  await detail.locator('summary').click();await detail.getByRole('checkbox',{name:/Просмотр: Список/}).check()
  // Failed save must retain the administrator's draft.
  await page.route('**/api/access-roles',route=>route.request().method()==='POST'?route.abort('failed'):route.continue())
  await form.getByRole('button',{name:'Сохранить роль',exact:true}).click()
  await expect(page.getByRole('alert')).toContainText('Не удалось связаться')
  await expect(form.getByLabel('Название роли',{exact:true})).toHaveValue(name)
  await page.unroute('**/api/access-roles')
  await form.getByRole('button',{name:'Сохранить роль',exact:true}).click()
  await expect(page.getByRole('status')).toContainText('Роль сохранена')
  const roles=await(await request.get(`${api}/access-roles`,{headers})).json(),role=roles.find((r:any)=>r.name===name)
  expect(role).toMatchObject({baseRole:'BRIGADIER',canJoinBrigade:true,permissions:['work-types.findAll']})
  await page.getByRole('link',{name:'Перейти к сотрудникам',exact:true}).click()
  const create=page.getByRole('form',{name:'Создание сотрудника'})
  await expect(create.getByRole('button',{name:'Создать пользователя',exact:true})).toBeEnabled()
  await create.getByLabel('Роль доступа',{exact:true}).selectOption(`custom:${role.id}`)
  await create.getByLabel('Бригада',{exact:true}).selectOption(String(brigade.id))
  await create.getByLabel('ФИО',{exact:true}).fill(name)
  await create.getByLabel('Логин сотрудника',{exact:true}).fill(username)
  await create.getByLabel('Пароль сотрудника',{exact:true}).fill(password)
  await create.getByRole('button',{name:'Создать пользователя',exact:true}).click()
  const row=page.getByRole('row').filter({has:page.getByRole('cell',{name:username,exact:true})})
  await expect(row).toContainText(name);await page.reload();await expect(row).toContainText(brigade.name)
  await row.getByRole('button',{name:'Изменить',exact:true}).click()
  const edit=page.getByRole('form',{name:'Редактирование сотрудника'})
  await expect(edit.getByLabel('Роль доступа',{exact:true})).toHaveValue(`custom:${role.id}`)
  await expect(edit.getByLabel('Бригада',{exact:true})).toHaveValue(String(brigade.id))
  await page.getByRole('button',{name:'Выйти',exact:true}).click()
  await page.getByLabel('Логин',{exact:true}).fill(username);await page.getByLabel('Пароль',{exact:true}).fill(password)
  await page.getByRole('button',{name:'Войти',exact:true}).click()
  await expect(page).toHaveURL(/\/access-home$/)
  await page.getByRole('link',{name:'Виды работ',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Виды работ',exact:true})).toBeVisible()
  await expect(page.getByRole('button',{name:'Добавить',exact:true})).toBeDisabled()
  await page.goto('/admin/users');await expect(page).toHaveURL(/\/access-home$/)
  const employee=await request.post(`${api}/auth/login`,{data:{username,password}});expect(employee.ok()).toBeTruthy()
  const employeeHeaders={Authorization:`Bearer ${(await employee.json()).accessToken}`}
  expect((await request.post(`${api}/work-types`,{headers:employeeHeaders,data:{name:'Denied'}})).status()).toBe(403)
  expect((await request.get(`${api}/access-roles`,{headers:employeeHeaders})).status()).toBe(403)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
  expect(errors).toEqual([])
  await page.screenshot({path:info.outputPath('custom-role-cabinet.png'),fullPage:true})
})
