import { test, expect } from 'playwright/test'

const api = 'http://localhost:3002/api'
test.use({ extraHTTPHeaders: { 'X-Forwarded-For': '10.30.0.74' } })

test('user form filters brigades by role and persists brigadier ИТР on create/edit/reload', async ({ page, request }, info) => {
  const suffix = `${Date.now()}-${info.project.name}`, password = 'brigade-browser-password'
  const login = await request.post(`${api}/auth/login`, { data: { username: process.env.ADMIN_USERNAME || 'e2e-admin', password: process.env.ADMIN_PASSWORD || 'e2e-admin-password' } })
  expect(login.ok()).toBeTruthy()
  const headers = { Authorization: `Bearer ${(await login.json()).accessToken}` }
  async function brigade(name: string, isActive = true) {
    const r = await request.post(`${api}/brigades`, { headers, data: { name: `${name} ${suffix}`, isActive } }); expect(r.ok()).toBeTruthy(); return r.json()
  }
  const itr = await brigade('ИТР'), other = await brigade('Монтаж'), inactive = await brigade('Архив', false), occupied = await brigade('Занятая')
  expect((await request.post(`${api}/users`, { headers, data: { fullName: `Другой ${suffix}`, username: `other-${suffix}`, password, role: 'BRIGADIER', brigadeId: occupied.id } })).ok()).toBeTruthy()
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await page.goto('/admin/users')
  await page.getByLabel('Логин', { exact: true }).fill(process.env.ADMIN_USERNAME || 'e2e-admin')
  await page.getByLabel('Пароль', { exact: true }).fill(process.env.ADMIN_PASSWORD || 'e2e-admin-password')
  await page.getByRole('button', { name: 'Войти', exact: true }).click()
  const create = page.getByRole('form', { name: 'Создание сотрудника', exact: true })
  await expect(create.getByRole('button', { name: 'Создать пользователя', exact: true })).toBeEnabled()
  const role = create.getByLabel('Роль доступа', { exact: true }), team = create.getByLabel('Бригада', { exact: true })
  await expect(team.locator(`option[value="${inactive.id}"]`)).toHaveCount(0)
  await expect(team.locator(`option[value="${occupied.id}"]`)).toHaveCount(1)
  await team.selectOption(String(occupied.id))
  await role.selectOption('BRIGADIER')
  await expect(team).toHaveValue(''); await expect(team.locator(`option[value="${occupied.id}"]`)).toHaveCount(0)
  await team.selectOption(String(itr.id))
  await role.selectOption('ACCOUNTANT'); await expect(team).toBeDisabled(); await expect(team).toHaveValue('')
  await role.selectOption('BRIGADIER'); await team.selectOption(String(itr.id))
  const name = `Бригадир ИТР ${suffix}`, username = `itr-${suffix}`
  await create.getByLabel('ФИО', { exact: true }).fill(name)
  await create.getByLabel('Логин сотрудника', { exact: true }).fill(username)
  await create.getByLabel('Пароль сотрудника', { exact: true }).fill(password)
  await page.route('**/api/users', route => route.request().method() === 'POST' ? route.abort('failed') : route.continue())
  await create.getByRole('button', { name: 'Создать пользователя', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Не удалось связаться с сервером')
  await expect(role).toHaveValue('BRIGADIER'); await expect(team).toHaveValue(String(itr.id))
  await page.unroute('**/api/users')
  await create.getByRole('button', { name: 'Создать пользователя', exact: true }).click()
  const row = page.getByRole('row').filter({ has: page.getByRole('cell', { name: username, exact: true }) })
  await expect(row).toContainText(itr.name); await expect(row).toContainText('Бригадир')
  const users = await (await request.get(`${api}/users`, { headers })).json(), saved = users.find((u: any) => u.username === username)
  expect(saved).toMatchObject({ role: 'BRIGADIER', brigadeId: itr.id })
  expect(await (await request.get(`${api}/brigades/${itr.id}`, { headers })).json()).toMatchObject({ brigadierId: saved.id, workerIds: [saved.id] })
  await page.reload(); await expect(row).toContainText(itr.name)
  await row.getByRole('button', { name: 'Изменить', exact: true }).click()
  const edit = page.getByRole('form', { name: 'Редактирование сотрудника', exact: true })
  await expect(edit.getByLabel('Бригада', { exact: true })).toHaveValue(String(itr.id))
  await edit.getByLabel('Бригада', { exact: true }).selectOption(String(other.id))
  await edit.getByRole('button', { name: 'Сохранить', exact: true }).click(); await expect(edit).toHaveCount(0)
  await page.reload(); await expect(row).toContainText(other.name)
  expect(await (await request.get(`${api}/brigades/${itr.id}`, { headers })).json()).toMatchObject({ brigadierId: null, workerIds: [] })
  expect(await (await request.get(`${api}/brigades/${other.id}`, { headers })).json()).toMatchObject({ brigadierId: saved.id, workerIds: [saved.id] })
  await row.getByRole('button', { name: 'Изменить', exact: true }).click()
  await edit.getByLabel('Роль доступа', { exact: true }).selectOption('ACCOUNTANT')
  await expect(edit.getByLabel('Бригада', { exact: true })).toHaveValue('')
  await edit.getByRole('button', { name: 'Сохранить', exact: true }).click(); await expect(edit).toHaveCount(0)
  await expect(row).toContainText('Бухгалтер')
  expect(await (await request.get(`${api}/brigades/${other.id}`, { headers })).json()).toMatchObject({ brigadierId: null, workerIds: [] })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath('brigade-membership.png'), fullPage: true })
  expect(errors).toEqual([])
})
