import { test, expect } from 'playwright/test'

test('director maintains combined structure, employee reporting and process ownership on desktop and mobile', async ({page,context,request},info)=>{
  const api='http://localhost:3002/api',suffix=`${Date.now()}-${info.project.name}`,password='organization-browser-password'
  const ip=`10.78.${info.project.name.startsWith('mobile')?2:1}.1`
  await context.setExtraHTTPHeaders({'X-Forwarded-For':ip})
  const login=await request.post(`${api}/auth/login`,{headers:{'X-Forwarded-For':ip},data:{username:process.env.ADMIN_USERNAME||'e2e-admin',password:process.env.ADMIN_PASSWORD||'e2e-admin-password'}})
  expect(login.ok()).toBeTruthy()
  const headers={Authorization:`Bearer ${(await login.json()).accessToken}`,'X-Forwarded-For':ip}
  const create=async(path:string,data:unknown)=>{const r=await request.post(api+path,{headers,data});expect(r.ok(),await r.text()).toBeTruthy();return r.json()}
  const positions=await (await request.get(`${api}/job-positions`,{headers})).json()
  const employee=await create('/users',{username:`org-worker-${suffix}`,fullName:`Снабженец ${suffix}`,password,role:'WORKER',positionId:positions.find((p:any)=>p.name==='Менеджер по снабжению').id})
  const director=await create('/users',{username:`org-director-${suffix}`,fullName:`Руководитель ${suffix}`,password,role:'DIRECTOR'})
  const object=await create('/objects',{name:`Орг объект ${suffix}`})
  const brigade=await create('/brigades',{name:`Орг бригада ${suffix}`})
  const process=await create('/business-processes/definitions',{title:`Снабжение ${suffix}`,description:'Заявка и приёмка',initialStageId:'request',fields:[],stages:[
    {id:'request',label:'Заявка',roles:['ADMIN'],requiredFields:[],nextStages:['done']},
    {id:'done',label:'Принято',roles:['ADMIN'],requiredFields:[],nextStages:[]},
  ]})
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  await page.goto('/admin/users')
  await page.getByLabel('Логин',{exact:true}).fill(director.username)
  await page.getByLabel('Пароль',{exact:true}).fill(password)
  await page.getByRole('button',{name:'Войти',exact:true}).click()
  await page.getByRole('link',{name:'Структура и ответственность →',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Структура и ответственность',exact:true})).toBeVisible()
  const general=page.getByRole('article',{name:'Подразделение Генеральный директор',exact:true})
  await expect(general).toContainText('Руководитель: Не назначен')
  await expect(page.getByRole('article',{name:'Подразделение Качество и стандартизация',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Добавить подразделение',exact:true}).click()
  const form=page.getByRole('form',{name:'Редактор подразделения',exact:true}),name=`Объект ${suffix}`
  await form.getByRole('textbox',{name:'Название подразделения',exact:true}).fill(name)
  await form.getByRole('combobox',{name:'Тип подразделения',exact:true}).selectOption('OBJECT')
  const directory=await (await request.get(`${api}/organization`,{headers})).json()
  await form.getByRole('combobox',{name:'Вышестоящее подразделение',exact:true}).selectOption(String(directory.units.find((n:any)=>n.seed_key==='production').id))
  await form.getByRole('combobox',{name:'Руководитель подразделения',exact:true}).selectOption(String(director.id))
  await form.getByRole('combobox',{name:'Связанный объект',exact:true}).selectOption(String(object.id))
  await form.getByRole('combobox',{name:'Связанная бригада',exact:true}).selectOption(String(brigade.id))
  await form.getByRole('textbox',{name:'Функции и ожидаемый результат',exact:true}).fill('Подготовить материалы к началу смены')
  await page.route('**/api/organization/units',route=>route.abort('failed'))
  await form.getByRole('button',{name:'Сохранить подразделение',exact:true}).click()
  await expect(page.getByRole('alert')).toContainText('Не удалось связаться с сервером')
  await expect(form.getByRole('textbox',{name:'Название подразделения',exact:true})).toHaveValue(name)
  await page.unroute('**/api/organization/units')
  await form.getByRole('button',{name:'Сохранить подразделение',exact:true}).click()
  await expect(page.getByRole('status')).toContainText('Изменения сохранены')
  const card=page.getByRole('article',{name:`Подразделение ${name}`,exact:true})
  await expect(card).toContainText(director.fullName)
  await expect(card).toContainText(object.name)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
  await page.screenshot({path:info.outputPath('organization-structure.png'),fullPage:true})
  await page.getByRole('button',{name:'Состав подразделений',exact:true}).click()
  await page.getByRole('searchbox',{name:'Поиск сотрудника',exact:true}).fill(employee.fullName)
  const personCard=page.getByRole('listitem',{name:`Сотрудник ${employee.fullName}`,exact:true})
  await expect(personCard).toContainText('Менеджер по снабжению')
  await personCard.getByRole('button',{name:'Назначить',exact:true}).click()
  const employeeForm=page.getByRole('form',{name:'Назначение сотрудника',exact:true})
  const created=(await (await request.get(`${api}/organization`,{headers})).json()).units.find((n:any)=>n.name===name)
  await employeeForm.getByRole('combobox',{name:'Подразделение сотрудника',exact:true}).selectOption(String(created.id))
  await employeeForm.getByRole('combobox',{name:'Прямой руководитель',exact:true}).selectOption(String(director.id))
  await employeeForm.getByRole('textbox',{name:'Зона ответственности сотрудника',exact:true}).fill('Согласованные закупки и сроки поставок')
  await employeeForm.getByRole('button',{name:'Сохранить назначение',exact:true}).click()
  await expect(personCard).toContainText(name)
  await expect(personCard).toContainText('Согласованные закупки и сроки поставок')
  await page.reload()
  await page.getByRole('button',{name:'Состав подразделений',exact:true}).click()
  await page.getByRole('searchbox',{name:'Поиск сотрудника',exact:true}).fill(employee.fullName)
  await expect(personCard).toContainText(name)
  await expect(personCard).toContainText(director.fullName)
  await personCard.getByRole('button',{name:'Назначить',exact:true}).click()
  const saved=(await (await request.get(`${api}/organization`,{headers})).json()).employees.find((p:any)=>p.user_id===employee.id)
  expect((await request.put(`${api}/organization/employees/${employee.id}`,{headers,data:{unitId:created.id,managerId:director.id,duties:'Изменено в другой вкладке',revision:saved.revision}})).ok()).toBeTruthy()
  await employeeForm.getByRole('textbox',{name:'Зона ответственности сотрудника',exact:true}).fill('Устаревший редактор')
  await employeeForm.getByRole('button',{name:'Сохранить назначение',exact:true}).click()
  await expect(page.getByRole('alert')).toContainText('Запись уже изменена')
  await page.getByRole('button',{name:'Обновить структуру',exact:true}).click()
  await expect(personCard).toContainText('Изменено в другой вкладке')
  await page.screenshot({path:info.outputPath('organization-members.png'),fullPage:true})
  await page.getByRole('button',{name:'Ответственность за процессы',exact:true}).click()
  const processCard=page.getByRole('listitem',{name:`Процесс ${process.schema.title}`,exact:true})
  await processCard.getByRole('button',{name:'Назначить ответственных',exact:true}).click()
  const processForm=page.getByRole('form',{name:'Ответственность за процесс',exact:true})
  await processForm.getByRole('combobox',{name:'Подразделение процесса',exact:true}).selectOption(String(created.id))
  await processForm.getByRole('combobox',{name:'Владелец процесса',exact:true}).selectOption(String(director.id))
  await processForm.getByRole('button',{name:'Сохранить ответственность',exact:true}).click()
  await expect(processCard).toContainText(director.fullName)
  await page.getByRole('button',{name:'История назначений',exact:true}).click()
  await expect(page.getByText(`Ответственность за процесс: ${process.schema.title}`,{exact:true})).toBeVisible()
  await expect(page.getByText(`Создание подразделения: ${name}`,{exact:true})).toBeVisible()
  const user=await (await request.get(`${api}/users/${employee.id}`,{headers})).json()
  expect(user.role).toBe('WORKER');expect(user.brigadeId).toBeNull()
  await page.route('**/api/organization',route=>route.abort('failed'))
  await page.reload()
  await expect(page.getByRole('alert')).toContainText('Не удалось связаться с сервером')
  await expect(page.getByRole('button',{name:'Добавить подразделение',exact:true})).toHaveCount(0)
  await page.unroute('**/api/organization')
  await page.getByRole('button',{name:'Повторить загрузку',exact:true}).click()
  await expect(card).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
  expect(errors).toEqual([])
})
