import { test, expect, mapTiles, type Page, type APIRequestContext } from './map-fixture'
import type { Locator, Route } from 'playwright/test'

const api = 'http://localhost:3002/api'

async function fixture(page: Page, request: APIRequestContext, suffix: string, ip: string) {
  const username = process.env.ADMIN_USERNAME || 'e2e-admin'
  const password = process.env.ADMIN_PASSWORD || 'e2e-admin-password'
  const auth = await request.post(`${api}/auth/login`, { headers: { 'X-Forwarded-For': ip }, data: { username, password } })
  expect(auth.ok()).toBeTruthy()
  const headers = { Authorization: `Bearer ${(await auth.json()).accessToken}`, 'X-Forwarded-For': ip }
  const response = await request.post(`${api}/objects`, { headers, data: { name: `Map ${suffix}` } })
  expect(response.ok()).toBeTruthy()
  const object = await response.json()
  await page.goto('/login')
  await page.getByLabel('Логин', { exact: true }).fill(username)
  await page.getByLabel('Пароль', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Войти', exact: true }).click()
  await expect(page).not.toHaveURL(/\/login$/)
  await page.goto('/admin/objects')
  const create = page.getByRole('form', { name: 'Добавить участок', exact: true })
  await create.getByLabel('Объект участка').selectOption(String(object.id))
  await create.getByPlaceholder('Название участка *').fill(`Map section ${suffix}`)
  return { headers, create, sectionName: `Map section ${suffix}` }
}

async function selectPoint(form: Locator, mobile: boolean, x = 160) {
  const map = form.getByRole('application', { name: 'Карта местоположения участка', exact: true })
  if (mobile) await map.tap({ position: { x, y: 140 } })
  else await map.click({ position: { x, y: 140 } })
  await expect(map.locator('.section-location-marker')).toHaveCount(1)
  return {
    latitude: Number(await form.getByLabel('Широта', { exact: true }).inputValue()),
    longitude: Number(await form.getByLabel('Долгота', { exact: true }).inputValue()),
  }
}

test('map selects and persists a section point; edit, radius, rejected GPS, failed save and QR remain consistent', async ({ page, context, request }, info) => {
  const mobile = info.project.name.startsWith('mobile')
  const ip = `10.81.${mobile ? 2 : 1}.1`
  await context.setExtraHTTPHeaders({ 'X-Forwarded-For': ip })
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  const { headers, create, sectionName } = await fixture(page, request, `${Date.now()}-${info.project.name}`, ip)
  const map = create.getByRole('application', { name: 'Карта местоположения участка', exact: true })
  await expect(map).toBeVisible()
  await expect(create.getByLabel('Широта', { exact: true })).toHaveValue('')
  await expect(map.locator('.section-location-marker')).toHaveCount(0)
  await map.getByRole('button', { name: 'Приблизить', exact: true }).click()
  await map.focus()
  await map.press('ArrowRight')
  await expect(create.getByLabel('Долгота', { exact: true })).toHaveValue('')
  await create.getByLabel('Радиус, м', { exact: true }).fill('250')
  const selected = await selectPoint(create, mobile)
  expect(selected.latitude).toBeGreaterThan(50)
  expect(selected.longitude).toBeGreaterThan(50)
  const circle = map.locator('.section-location-radius')
  await expect(circle).toHaveCount(1)
  const originalCircle = await circle.getAttribute('d')
  await create.getByLabel('Радиус, м', { exact: true }).fill('400')
  await expect(circle).not.toHaveAttribute('d', originalCircle!)
  await create.getByLabel('Радиус, м', { exact: true }).fill('5001')
  await expect(circle).toHaveCount(0)
  await create.getByRole('button', { name: 'Сохранить участок', exact: true }).click()
  await expect(create.getByRole('alert')).toContainText('от 10 до 5000')
  await create.getByLabel('Радиус, м', { exact: true }).fill('250')
  await create.getByRole('button', { name: 'Сохранить участок', exact: true }).click()
  const row = page.getByRole('row').filter({ has: page.getByRole('cell', { name: sectionName, exact: true }) })
  await expect(row).toContainText('Радиус 250 м')
  const qr = await row.getByRole('link', { name: 'открыть', exact: true }).getAttribute('href')
  const sections = await request.get(`${api}/sections`, { headers })
  expect(sections.ok()).toBeTruthy()
  const section = (await sections.json()).find((item: { name: string }) => item.name === sectionName)
  expect(section).toMatchObject({ ...selected, radiusMeters: 250 })
  await page.reload()
  await row.getByRole('button', { name: 'Изменить', exact: true }).click()
  const edit = page.getByRole('form', { name: 'Редактирование участка', exact: true })
  await expect(edit.getByLabel('Широта', { exact: true })).toHaveValue(String(selected.latitude))
  await expect(edit.locator('.section-location-marker')).toHaveCount(1)
  await expect(edit.locator('.section-location-radius')).toHaveCount(1)
  await edit.getByLabel('Радиус, м', { exact: true }).fill('300')
  const moved = await selectPoint(edit, mobile, 200)
  expect(moved).not.toEqual(selected)
  await expect(create.getByLabel('Широта', { exact: true })).toHaveValue('')
  await context.setGeolocation({ latitude: 52, longitude: 52, accuracy: 500 })
  await edit.getByRole('button', { name: 'Я на участке — определить координаты', exact: true }).click()
  await expect(edit.getByRole('status')).toContainText('Координаты не изменены')
  await expect(edit.getByLabel('Широта', { exact: true })).toHaveValue(moved.latitude.toFixed(6))
  const endpoint = `**/api/sections/${section.id}`
  await page.route(endpoint, route => route.request().method() === 'PATCH' ? route.abort('failed') : route.continue())
  await edit.getByRole('button', { name: 'Сохранить', exact: true }).click()
  await expect(edit.getByRole('alert')).toContainText('Не удалось связаться с сервером')
  await expect(edit.getByLabel('Радиус, м', { exact: true })).toHaveValue('300')
  await expect(edit.getByLabel('Широта', { exact: true })).toHaveValue(moved.latitude.toFixed(6))
  await page.unroute(endpoint)
  await edit.getByRole('button', { name: 'Отмена', exact: true }).click()
  await row.getByRole('button', { name: 'Изменить', exact: true }).click()
  await expect(edit.getByLabel('Широта', { exact: true })).toHaveValue(String(selected.latitude))
  await expect(edit.getByLabel('Радиус, м', { exact: true })).toHaveValue('250')
  await edit.getByLabel('Радиус, м', { exact: true }).fill('300')
  const finalPoint = await selectPoint(edit, mobile, 200)
  await edit.screenshot({ path: info.outputPath('section-map-editor.png') })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await edit.getByRole('button', { name: 'Сохранить', exact: true }).click()
  await expect(edit).toHaveCount(0)
  await page.reload()
  await expect(row).toContainText('Радиус 300 м')
  await expect(row.getByRole('link', { name: 'открыть', exact: true })).toHaveAttribute('href', qr!)
  const saved = await request.get(`${api}/sections/${section.id}`, { headers })
  expect(saved.ok()).toBeTruthy()
  expect(await saved.json()).toMatchObject({ ...finalPoint, radiusMeters: 300, code: section.code, name: sectionName })
  expect(errors).toEqual([])
})

test('map tile outage retains manual coordinates; retry, zero coordinates and keyboard selection work', async ({ page, context, request }, info) => {
  const ip = `10.81.${info.project.name.startsWith('mobile') ? 2 : 1}.2`
  await context.setExtraHTTPHeaders({ 'X-Forwarded-For': ip })
  const failTiles = (route: Route) => route.abort('failed')
  await page.route(mapTiles, failTiles)
  const { create } = await fixture(page, request, `${Date.now()}-offline-${info.project.name}`, ip)
  await expect(create.getByRole('note')).toContainText('Не удалось загрузить карту')
  await expect(create.getByLabel('Широта', { exact: true })).toHaveValue('')
  await create.getByLabel('Широта', { exact: true }).fill('0')
  await create.getByLabel('Долгота', { exact: true }).fill('0')
  await expect(create.locator('.section-location-marker')).toHaveCount(1)
  await expect(create.locator('.section-location-radius')).toHaveCount(1)
  await create.getByLabel('Широта', { exact: true }).fill('91')
  await expect(create.locator('.section-location-marker')).toHaveCount(0)
  await expect(create.locator('.section-location-radius')).toHaveCount(0)
  await create.getByLabel('Широта', { exact: true }).fill('51,2301')
  await create.getByLabel('Долгота', { exact: true }).fill('51,3701')
  await expect(create.locator('.section-location-marker')).toHaveCount(1)
  await page.unroute(mapTiles, failTiles)
  await create.getByRole('button', { name: 'Повторить загрузку карты', exact: true }).click()
  await expect(create.getByRole('note')).toHaveCount(0)
  await expect(create.locator('.leaflet-tile-loaded').first()).toBeVisible()
  await expect(create.getByLabel('Широта', { exact: true })).toHaveValue('51,2301')
  const map = create.getByRole('application', { name: 'Карта местоположения участка', exact: true })
  await map.focus()
  await map.press('ArrowRight')
  const button = create.getByRole('button', { name: 'Поставить точку в центре карты', exact: true })
  await button.focus()
  await button.press('Enter')
  await expect(create.getByLabel('Долгота', { exact: true })).not.toHaveValue('51,3701')
  await expect(create.getByLabel('Широта', { exact: true })).not.toHaveValue('')
  await expect(create.locator('.section-location-marker')).toHaveCount(1)
})
