import { useEffect, useState } from 'react'
import { fetchKpi, type KpiData } from '@/api/operationsApi'
import { toUserMessage } from '@/api/client'
import { businessDateString } from '@/lib/businessDate'
const groupLabels = { employee: 'По сотрудникам', brigade: 'По бригадам', object: 'По объектам' } as const

export function KpiPage() {
  const [anchor, setAnchor] = useState(businessDateString)
  const [period, setPeriod] = useState<'day' | 'week' | 'month'>('week')
  const [groupBy, setGroupBy] = useState<'employee' | 'brigade' | 'object'>('brigade')
  const [data, setData] = useState<KpiData | null>(null)
  const [error, setError] = useState<string | null>(null)
  useEffect(() => { void fetchKpi({ anchor, period, groupBy }).then(setData).catch((e) => setError(toUserMessage(e))) }, [anchor, period, groupBy])
  return <div className="space-y-5"><div><h1 className="text-2xl font-black">KPI и качество</h1><p className="text-sm text-slate-500">Только подтверждаемые метрики из времени, GPS, фото, чек-листов и приёмки</p></div><div className="flex flex-wrap gap-3 rounded-2xl border bg-white p-4"><input type="date" value={anchor} onChange={(e) => setAnchor(e.target.value)} className="rounded-xl border px-3 py-2"/><select value={period} onChange={(e) => setPeriod(e.target.value as typeof period)} className="rounded-xl border px-3 py-2"><option value="day">День</option><option value="week">Неделя</option><option value="month">Месяц</option></select><select value={groupBy} onChange={(e) => setGroupBy(e.target.value as typeof groupBy)} className="rounded-xl border px-3 py-2">{Object.entries(groupLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select>{data && <span className="self-center text-sm text-slate-500">{data.filters.dateFrom} — {data.filters.dateTo}</span>}</div>{data && <p className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">{data.disclaimer}</p>}{error && <p className="rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}<div className="overflow-x-auto rounded-2xl border bg-white"><table className="min-w-[1100px] w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="p-3">{groupLabels[groupBy]}</th><th className="p-3 text-right">Работ</th><th className="p-3 text-right">Принято</th><th className="p-3 text-right">В срок</th><th className="p-3 text-right">Просрочки</th><th className="p-3 text-right">Опоздания</th><th className="p-3 text-right">Ср. время</th><th className="p-3 text-right">Повторные</th><th className="p-3 text-right">Отклонено</th><th className="p-3 text-right">Материалы</th><th className="p-3 text-right">Маршрут</th></tr></thead><tbody className="divide-y">{data?.rows.map((row) => <tr key={row.key}><td className="p-3 font-bold">{row.name}<small className="block text-slate-400">{row.objectCount} объектов</small></td><td className="p-3 text-right">{row.executions}</td><td className="p-3 text-right font-bold text-emerald-700">{row.acceptedPercent}%</td><td className="p-3 text-right">{row.completedOnTime}</td><td className="p-3 text-right text-red-700">{row.overdue}</td><td className="p-3 text-right text-amber-700">{row.lateArrivals}</td><td className="p-3 text-right">{row.averageDurationMinutes == null ? '—' : `${row.averageDurationMinutes} мин`}</td><td className="p-3 text-right">{row.reworks}</td><td className="p-3 text-right">{row.rejected}</td><td className="p-3 text-right">{row.materialQuantity}</td><td className="p-3 text-right">{row.routeCompliancePercent}%</td></tr>)}</tbody></table>{data?.rows.length === 0 && <p className="p-10 text-center text-slate-500">Нет доказательных данных за период</p>}</div></div>
}
