export enum StockMovementType {
  IMPORT = 'IMPORT',
  INCOME = 'INCOME',
  OUTCOME = 'OUTCOME',
  RETURN = 'RETURN',
  TRANSFER = 'TRANSFER',
  RESERVE = 'RESERVE',
  RELEASE = 'RELEASE',
  WRITE_OFF = 'WRITE_OFF',
  CORRECTION = 'CORRECTION',
}
