export enum UserRole {
  DIRECTOR = 'DIRECTOR',
  ADMIN = 'ADMIN',
  ACCOUNTANT = 'ACCOUNTANT',
  BRIGADIER = 'BRIGADIER',
  AGRONOMIST = 'AGRONOMIST',
  WORKER = 'WORKER',
  WATER_CARRIER = 'WATER_CARRIER',
  AKIMAT = 'AKIMAT',
  ANTICOR = 'ANTICOR',
}
