import { useCallback,useEffect,useRef,useState } from 'react'
import { Link,useParams } from 'react-router-dom'
import { useAuth } from '@/context/AuthContext'
import { AccountControls } from '@/components/AccountControls'
import { toUserMessage } from '@/api/client'
import { createStockMovement } from '@/api/productsApi'
import { workflowGet,workflowPost,type TaskFlow,type Catalog,type ToolItem,type Person } from '@/api/workflowApi'
import { Label,CheckList,inputClass,buttonClass,panelClass } from '@/components/workflow/Controls'
import { ReportForm,ObstacleCard,ImprovementCard } from '@/components/workflow/ImprovementForms'
import { ToolsPanel } from '@/components/workflow/ToolsPanel'
const eventNames:Record<string,string>={PLAN_CONFIGURED:'Задана подготовка',PREPARED:'Готовность подтверждена',STEPS_CHECKED:'Проверены шаги работы',OBSTACLE_REPORTED:'Сообщено о препятствии',OBSTACLE_ASSIGN:'Назначено устранение',OBSTACLE_RESOLVE:'Устранение передано на проверку',OBSTACLE_VERIFY:'Устранение подтверждено',OBSTACLE_REOPEN:'Препятствие возвращено',IMPROVEMENT_PROPOSED:'Предложено улучшение',IMPROVEMENT_PLAN:'Начат эксперимент',IMPROVEMENT_MEASURE:'Внесено измерение',IMPROVEMENT_ADOPT:'Утверждено новое правило',IMPROVEMENT_REJECT:'Предложение отклонено',TOOL_ISSUE:'Инструмент выдан',TOOL_RETURN:'Инструмент возвращён'}
export function TaskFlowPage() {
  const taskId=Number(useParams().taskId);const {user}=useAuth();const management=['ADMIN','DIRECTOR','BRIGADIER','AGRONOMIST'].includes(user!.role)
  const [data,setData]=useState<TaskFlow|null>(null);const [catalog,setCatalog]=useState<Catalog|null>(null);const [tools,setTools]=useState<ToolItem[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const [prep,setPrep]=useState<number[]>([]);const [steps,setSteps]=useState<number[]>([])
  const materialPending=useRef<Record<number,string>>({})
  const load=useCallback(async()=>{try {const [d,c,t]=await Promise.all([workflowGet<TaskFlow>(`/tasks/${taskId}`),workflowGet<Catalog>('/catalog'),workflowGet<ToolItem[]>('/tools')]);setData(d);setCatalog(c);setTools(t);setPrep(d.plan?.checked_preparation??[]);setSteps(d.plan?.completed_steps??[]);setError('')}catch(err){setError(toUserMessage(err));throw err}finally{setLoading(false)}},[taskId])
  useEffect(()=>{void load().catch(()=>undefined)},[load])
  async function saveChecks(stage:'prepare'|'steps') {setBusy(true);setError('');try{await workflowPost(`/tasks/${taskId}/${stage}`,{checked:stage==='prepare'?prep:steps});await load()}catch(err){setError(toUserMessage(err))}finally{setBusy(false)}}
  async function issueMaterial(productId:number,quantity:number) {if(!data)return;setBusy(true);setError('');try{materialPending.current[productId]??=crypto.randomUUID();await createStockMovement({productId,type:'OUTCOME',quantity,taskId,sectionId:data.task.section_id,objectId:data.task.object_id,employeeId:data.task.assignee_user_id,clientOperationId:materialPending.current[productId],purpose:`Подготовка задачи #${taskId}`});delete materialPending.current[productId];await load()}catch(err){setError(toUserMessage(err))}finally{setBusy(false)}}
  const people:Person[]=catalog?[...new Map([...catalog.people,...(data?[{id:data.task.assignee_user_id,name:data.task.assignee_name,role:'WORKER'},...data.obstacles.flatMap(o=>[{id:o.owner_id,name:o.owner_name,role:''},{id:o.reporter_id,name:o.reporter_name,role:''}])]:[])].filter(p=>p.id).map(p=>[p.id,p])).values()]:[]
  const back=management?'/admin/workflow':'/field/workflow'
  return <main className="min-h-screen bg-slate-50 px-4 py-5"><div className="mx-auto max-w-6xl space-y-5"><header className="flex flex-wrap items-center justify-between gap-3"><Link to={back} className="font-semibold text-blue-700">← Работа и улучшения</Link><AccountControls/></header>
    {error&&<div role="alert" className="rounded-xl bg-red-50 p-4 text-red-800">{error}<button type="button" className="ml-3 underline" onClick={()=>void load().catch(()=>undefined)}>Обновить данные</button></div>}
    {loading?<p role="status">Загрузка задачи…</p>:data&&catalog&&<><section className={panelClass}><p className="text-sm text-slate-500">Задача #{taskId}</p><h1 className="text-2xl font-bold">{data.task.description}</h1><p>{data.task.object_name} · {data.task.section_name}</p><p>Исполнитель: {data.task.assignee_name}</p>{data.plan&&<p>За результат: <b>{data.plan.accountable_name}</b> · Принимает: <b>{data.plan.reviewer_name}</b> · Лимит незавершённых задач: {data.plan.wip_limit}</p>}
    <div className="flex flex-wrap gap-3">{data.canExecute&&<Link className="rounded-lg bg-blue-700 px-4 py-2 font-semibold text-white" to={data.execution?`/field/executions/${data.execution.id}`:`/field/qr?taskId=${taskId}`}>{data.execution?'Открыть выполнение':'QR и прибытие'}</Link>}{data.canManage&&data.execution&&<Link to="/admin/executions" className="rounded-lg border px-4 py-2 font-semibold text-blue-700">Открыть приёмку</Link>}</div></section>
    <div className="grid items-start gap-5 lg:grid-cols-2"><div className="space-y-5">
    {data.canManage&&['ASSIGNED','ACCEPTED'].includes(data.task.status)&&!data.execution&&<PlanForm key={data.plan?`${data.plan.standard_id}:${data.plan.accountable_id}:${data.plan.reviewer_id}`:'new'} data={data} catalog={catalog} tools={tools} onChanged={load}/>}
    {!data.plan?<section className={panelClass}><h2 className="font-bold">Подготовка ещё не задана</h2><p>Руководителю нужно выбрать стандарт, ответственного и принимающего. После этого здесь появятся проверки готовности и шаги работы.</p><p className="text-sm text-slate-600">Для ранее созданных задач прежний процесс доступен до назначения стандарта.</p></section>:<section className={panelClass}><h2 className="text-lg font-bold">{data.plan.title} · версия {data.plan.version}</h2><p><b>Критерии приёмки:</b> {data.plan.acceptance}</p>
      {!!data.readiness.length&&<div className="rounded-xl bg-amber-50 p-3"><b>Что нужно подготовить</b><ul className="list-disc pl-5">{data.readiness.map((r,i)=><li key={i}>{r}</li>)}</ul></div>}
      <CheckList title="Перед началом" labels={data.plan.preparation} checked={prep} onChange={setPrep} disabled={busy||!data.canExecute||['COMPLETED','VERIFIED','CANCELLED'].includes(data.task.status)}/>
      {data.canExecute&&!['COMPLETED','VERIFIED','CANCELLED'].includes(data.task.status)&&<button type="button" className={buttonClass} disabled={busy} onClick={()=>void saveChecks('prepare')}>Подтвердить подготовку</button>}
      {data.plan.ready_at&&<p className="text-sm text-emerald-700">Подготовка подтверждена {new Date(data.plan.ready_at).toLocaleString('ru-RU')}. Перед стартом сервер повторно проверяет препятствия и ресурсы.</p>}
      <CheckList title="Шаги работы" labels={data.plan.steps} checked={steps} onChange={setSteps} disabled={busy||!data.canExecute||!['IN_PROGRESS','REJECTED'].includes(data.task.status)}/>
      {data.canExecute&&['IN_PROGRESS','REJECTED'].includes(data.task.status)&&<button type="button" className={buttonClass} disabled={busy} onClick={()=>void saveChecks('steps')}>Сохранить выполненные пункты</button>}
    </section>}
    {!!data.materials.length&&<section className={panelClass}><h2 className="font-bold">Материалы для задачи</h2>{data.materials.map(m=><div key={m.productId} className="rounded-lg border p-3"><b>{m.name}</b><p>Нужно: {m.required} · Выдано: {m.issued} · Осталось выдать: {m.missing}</p>{m.missing>0&&data.canManage&&['ADMIN','DIRECTOR','BRIGADIER'].includes(user!.role)&&<button type="button" className={buttonClass} disabled={busy} onClick={()=>void issueMaterial(m.productId,m.missing)}>Выдать недостающее</button>}</div>)}<p className="text-sm">Выдача записывается в существующий склад и привязывается к этой задаче.</p></section>}
    {!!data.tools.length&&<section className={panelClass}><h2 className="font-bold">Комплект инструмента</h2><ToolsPanel tools={data.tools} tasks={[{id:taskId,description:data.task.description,stage:data.task.status==='COMPLETED'?'REVIEW':data.task.status==='VERIFIED'?'DONE':data.task.status==='CANCELLED'?'CANCELLED':'PLANNED'} as import('@/api/workflowApi').BoardTask]} onChanged={load}/></section>}
    </div><div className="space-y-5"><ReportForm taskId={taskId} obstacles={data.obstacles} onChanged={load}/><section className="space-y-3"><h2 className="text-xl font-bold">Препятствия · {data.obstacles.length}</h2>{!data.obstacles.length&&<p className="text-slate-600">О препятствиях пока не сообщали.</p>}{data.obstacles.map(o=><ObstacleCard key={`${o.id}:${o.status}:${o.owner_id}`} item={o} people={people} canManage={data.canManage} onChanged={load}/>)}</section><section className="space-y-3"><h2 className="text-xl font-bold">Предложения · {data.improvements.length}</h2>{!data.improvements.length&&<p className="text-slate-600">Предложений пока нет.</p>}{data.improvements.map(i=><ImprovementCard key={`${i.id}:${i.status}`} item={i} people={people} canManage={data.canManage} canAdopt={data.canAdopt} onChanged={load}/>)}</section></div></div>
    <details className={panelClass}><summary className="cursor-pointer font-bold">История изменений</summary>{!data.events.length?<p>Изменений пока нет.</p>:<ul className="space-y-2">{data.events.map(e=><li key={e.id} className="border-b py-2 text-sm">{eventNames[e.kind]??'Обновление'} · {e.actor_name} · {new Date(e.created_at).toLocaleString('ru-RU')}</li>)}</ul>}</details>
    </>}
  </div></main>
}
function PlanForm({data,catalog,tools,onChanged}:{data:TaskFlow;catalog:Catalog;tools:ToolItem[];onChanged:()=>Promise<void>}) {
  const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [materials,setMaterials]=useState(data.plan?.materials??[])
  const standards=catalog.standards.filter(s=>s.work_type_id===data.task.work_type_id)
  if(data.plan&&!standards.some(s=>s.id===data.plan!.standard_id)) standards.push({id:data.plan.standard_id,work_type_id:data.task.work_type_id,title:data.plan.title,version:data.plan.version,steps:data.plan.steps,preparation:data.plan.preparation,acceptance:data.plan.acceptance,work_type_name:data.task.work_type_name})
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);setBusy(true);setError('');try{await workflowPost(`/tasks/${data.task.id}/plan`,{standardId:Number(d.get('standardId')),accountableId:Number(d.get('accountableId')),reviewerId:Number(d.get('reviewerId')),wipLimit:Number(d.get('wipLimit')),toolIds:d.getAll('toolId').map(Number),materials});await onChanged()}catch(err){setError(toUserMessage(err))}finally{setBusy(false)}}
  return <details className={panelClass} open={!data.plan}><summary className="cursor-pointer font-bold">Стандарт и ответственность</summary>{!standards.length?<p>Для этого вида работ ещё нет стандарта. Директор может создать его в разделе «Работа и улучшения → Стандарты».</p>:<form onSubmit={submit} className="space-y-3"><fieldset disabled={busy} className="space-y-3"><Label name="Стандарт задачи"><select name="standardId" className={inputClass} required defaultValue={data.plan?.standard_id??standards[0].id}>{standards.map(s=><option value={s.id} key={s.id}>{s.title} · версия {s.version}</option>)}</select></Label><Label name="Отвечает за результат"><select name="accountableId" className={inputClass} required defaultValue={data.plan?.accountable_id??''}><option value="">Выберите руководителя</option>{catalog.people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Label><Label name="Принимает работу"><select name="reviewerId" className={inputClass} required defaultValue={data.plan?.reviewer_id??''}><option value="">Выберите принимающего</option>{catalog.people.filter(p=>p.id!==data.task.assignee_user_id).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Label><Label name="Лимит незавершённых задач исполнителя"><input name="wipLimit" type="number" min={1} max={5} defaultValue={data.plan?.wip_limit??1} className={inputClass} required/></Label>
    <fieldset className="space-y-2"><legend className="font-bold">Необходимые инструменты</legend>{tools.filter(t=>t.state!=='RETIRED').map(t=><label key={t.id} className="flex gap-2"><input type="checkbox" name="toolId" value={t.id} defaultChecked={data.plan?.required_tool_ids.includes(t.id)}/>{t.code} · {t.name}</label>)}{!tools.length&&<p className="text-sm">Инструментов в реестре пока нет.</p>}</fieldset>
    <div className="space-y-3"><b>Необходимые материалы</b>{materials.map((m,i)=><div key={i} className="space-y-2 rounded-lg border p-3"><Label name={`Материал ${i+1}`}><select className={inputClass} value={m.productId||''} required onChange={e=>setMaterials(old=>old.map((v,n)=>n===i?{...v,productId:Number(e.target.value)}:v))}><option value="">Выберите материал</option>{catalog.products.map(p=><option key={p.id} value={p.id}>{p.name} · {p.unit}</option>)}</select></Label><Label name={`Количество материала ${i+1}`}><input className={inputClass} type="number" min="0.001" step="0.001" value={m.quantity||''} required onChange={e=>setMaterials(old=>old.map((v,n)=>n===i?{...v,quantity:Number(e.target.value)}:v))}/></Label><button type="button" onClick={()=>setMaterials(old=>old.filter((_,n)=>n!==i))} className="text-red-700 underline">Убрать материал</button></div>)}<button type="button" disabled={materials.length>=30} className="font-semibold text-blue-700 underline" onClick={()=>setMaterials(old=>[...old,{productId:0,quantity:0}])}>Добавить материал</button></div>
    <button type="submit" className={buttonClass}>Сохранить порядок работы</button></fieldset>{error&&<p role="alert" className="text-red-700">{error}</p>}</form>}</details>
}
