import { useState } from 'react'
import { Field, inputClass, buttonClass, secondaryClass, type Workspace } from './office-ui'

type Save=(path:string,body:Record<string,unknown>)=>Promise<boolean>
function Text({label,value,onChange,type='text',required=true}:{label:string;value:string;onChange:(v:string)=>void;type?:string;required?:boolean}){return <Field label={label}><input required={required} type={type} className={inputClass} value={value} onChange={e=>onChange(e.target.value)}/></Field>}
export function ProjectEditor({data,existing,busy,save,close,userId}:{data:Workspace;existing?:any;busy:boolean;save:Save;close:()=>void;userId:number}){
  const [title,setTitle]=useState(existing?.title??''),[description,setDescription]=useState(existing?.description??'')
  const [unit,setUnit]=useState(String(existing?.unit_id??data.access.unitId??'')),[owner,setOwner]=useState(String(existing?.owner_id??userId)),[start,setStart]=useState(existing?.start_date??data.today),[due,setDue]=useState(existing?.due_date??data.today),[status,setStatus]=useState(existing?.status??'ACTIVE')
  const [members,setMembers]=useState<number[]>(data.memberships.filter(m=>m.project_id===existing?.id).map(m=>m.user_id)),[units,setUnits]=useState<number[]>(data.projectUnits.filter(m=>m.project_id===existing?.id).map(m=>m.unit_id))
  function toggle(v:number,list:number[],set:(a:number[])=>void){set(list.includes(v)?list.filter(n=>n!==v):[...list,v])}
  return <form className="space-y-4" onSubmit={async e=>{e.preventDefault();if(await save('/office/projects',{id:existing?.id,revision:existing?.revision,title,description,unitId:Number(unit),ownerId:Number(owner),startDate:start,dueDate:due,status,memberIds:members,unitIds:units}))close()}}>
    <Text label="Название проекта" value={title} onChange={setTitle}/><Field label="Цель и результат"><textarea className={inputClass} value={description} onChange={e=>setDescription(e.target.value)}/></Field>
    <div className="grid gap-4 sm:grid-cols-2"><Field label="Подразделение проекта"><select required className={inputClass} value={unit} onChange={e=>setUnit(e.target.value)}><option value="">Выберите</option>{data.units.filter(u=>data.access.profile==='EXECUTIVE'||u.id===data.access.unitId).map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></Field><Field label="Ответственный менеджер"><select className={inputClass} value={owner} onChange={e=>setOwner(e.target.value)}>{data.employees.filter(u=>data.access.profile==='EXECUTIVE'||u.id===userId).map(u=><option key={u.id} value={u.id}>{u.full_name}</option>)}</select></Field><Text label="Начало проекта" type="date" value={start} onChange={setStart}/><Text label="Срок проекта" type="date" value={due} onChange={setDue}/></div>
    <fieldset className="rounded-xl border p-3"><legend>Участвующие подразделения</legend><p className="mb-2 text-sm text-slate-500">Их сотрудники с доступом «Подразделение» смогут работать в проекте в пределах своего профиля.</p><div className="grid gap-2 sm:grid-cols-2">{data.units.map(u=><label key={u.id} className="flex items-start gap-2 text-sm"><input type="checkbox" checked={units.includes(u.id)} onChange={()=>toggle(u.id,units,setUnits)}/>{u.name}</label>)}</div></fieldset>
    <fieldset className="rounded-xl border p-3"><legend>Лично назначенные участники</legend><div className="grid gap-2 sm:grid-cols-2">{data.employees.map(u=><label key={u.id} className="flex gap-2 text-sm"><input type="checkbox" checked={members.includes(u.id)} onChange={()=>toggle(u.id,members,setMembers)}/>{u.full_name}</label>)}</div></fieldset>
    {existing&&<Field label="Статус проекта"><select className={inputClass} value={status} onChange={e=>setStatus(e.target.value)}><option value="ACTIVE">В работе</option><option value="COMPLETED">Завершён</option><option value="ARCHIVED">Архив</option></select></Field>}
    <div className="flex gap-3"><button disabled={busy} className={buttonClass}>Сохранить проект</button><button type="button" onClick={close} className={secondaryClass}>Закрыть</button></div>
  </form>
}
const outline='Договор № {{number}} от {{date}}\n\nКонтрагент: {{counterparty}}\nРеквизиты сторон: {{requisites}}\n\nПредмет договора: {{subject}}\nСтоимость: {{amount}}\nУсловия оплаты: {{paymentTerms}}\nСроки: с {{startDate}} по {{endDate}}\n\n[Дополните порядок выполнения и приёмки, ответственность сторон, изменения, расторжение и подписи перед утверждением шаблона.]'
export function TemplateEditor({data,busy,save}:{data:Workspace;busy:boolean;save:Save}){
  const [id,setId]=useState(''),[title,setTitle]=useState(''),[body,setBody]=useState(outline),[approve,setApprove]=useState(false)
  return <form className="space-y-4" onSubmit={async e=>{e.preventDefault();const old=data.templates.find(t=>t.id===Number(id));if(await save('/office/templates',{id:id?Number(id):undefined,revision:old?.revision,title,body,approve})){setId('');setTitle('');setBody(outline);setApprove(false)}}}>
    <Field label="Шаблон"><select className={inputClass} value={id} onChange={e=>{setId(e.target.value);const t=data.templates.find(t=>t.id===Number(e.target.value));setTitle(t?.title??'');setBody(t?.body??outline);setApprove(false)}}><option value="">Новый шаблон</option>{data.templates.map(t=><option key={t.id} value={t.id}>{t.title} · версия {t.revision} · {t.approved?'утверждён':'черновик'}</option>)}</select></Field>
    <Text label="Название шаблона" value={title} onChange={setTitle}/><Field label="Текст договора с маркерами"><textarea required rows={16} className={inputClass} value={body} onChange={e=>setBody(e.target.value)}/></Field>
    <p className="text-sm text-slate-600">Начальный текст — заготовка. Дополните условия вашей компании. Маркеры: number, date, counterparty, requisites, subject, amount, paymentTerms, startDate, endDate в двойных фигурных скобках. Уже созданные договоры сохраняют свою версию текста.</p>
    <label className="flex items-start gap-2"><input type="checkbox" checked={approve} onChange={e=>setApprove(e.target.checked)}/>Условия проверены: утвердить эту версию для создания договоров</label><button className={buttonClass} disabled={busy}>Сохранить шаблон</button>
  </form>
}
export function RecordEditor({kind,projectId,data,busy,save,close}:{kind:string;projectId:number;data:Workspace;busy:boolean;save:Save;close:()=>void}){
  const [title,setTitle]=useState(''),[values,setValues]=useState<Record<string,string>>({dueDate:data.today,startDate:data.today,endDate:data.today,issueDate:data.today,date:data.today,quadrant:'2',direction:kind==='CONTRACT'?'SUPPLIER':'IN'}),[advance,setAdvance]=useState(false)
  const [checklist,setChecklist]=useState(''),[lines,setLines]=useState([{title:'',amount:''}]);const v=(k:string)=>values[k]??'',set=(k:string,value:string)=>setValues(old=>({...old,[k]:value}))
  const records=data.records.filter(r=>r.project_id===projectId),contracts=data.contractOptions.filter(c=>c.project_id===projectId),purchases=records.filter(r=>r.kind==='PURCHASE'&&['APPROVED','RECEIVED'].includes(r.status)),invoices=records.filter(r=>r.kind==='INVOICE'&&r.status==='APPROVED')
  const field=(key:string,label:string,type='text',required=true)=><Text key={key} label={label} value={v(key)} onChange={value=>set(key,value)} type={type} required={required}/>
  const select=(key:string,label:string,options:{id:number|string;label:string}[],required=true,onSelect?:(value:string)=>void)=><Field label={label}><select required={required} className={inputClass} value={v(key)} onChange={e=>{set(key,e.target.value);onSelect?.(e.target.value)}}><option value="">Выберите</option>{options.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select></Field>
  const textarea=(key:string,label:string,required=true)=><Field label={label}><textarea required={required} rows={3} className={inputClass} value={v(key)} onChange={e=>set(key,e.target.value)}/></Field>
  async function submit(e:React.FormEvent){e.preventDefault();let payload:Record<string,unknown>={}
    if(kind==='TASK')payload={assigneeId:Number(v('assigneeId')),dueDate:v('dueDate'),checklist:checklist.split('\n').map(s=>s.trim()).filter(Boolean),quadrant:Number(v('quadrant')),improvement:v('improvement')}
    if(kind==='CONTRACT')payload={templateId:Number(v('templateId')),counterparty:v('counterparty'),requisites:v('requisites'),subject:v('subject'),amount:v('amount'),paymentTerms:v('paymentTerms'),startDate:v('startDate'),endDate:v('endDate'),direction:v('direction')}
    if(kind==='BUDGET')payload={lines}
    if(kind==='PURCHASE')payload={amount:v('amount'),supplier:v('supplier'),purpose:v('purpose'),dueDate:v('dueDate'),contractId:v('contractId')?Number(v('contractId')):null}
    if(kind==='RECEIPT')payload={purchaseId:Number(v('purchaseId')),amount:v('amount'),date:v('date'),note:v('note')}
    if(kind==='INVOICE')payload={direction:v('direction'),amount:v('amount'),contractId:Number(v('contractId')),purchaseId:v('direction')==='IN'?Number(v('purchaseId')):null,externalNumber:v('externalNumber'),counterparty:v('counterparty'),requisites:v('requisites'),issueDate:v('issueDate'),dueDate:v('dueDate'),advance,advanceReason:v('advanceReason')}
    if(kind==='PAYMENT')payload={invoiceId:Number(v('invoiceId')),amount:v('amount'),date:v('date'),reference:v('reference')}
    if(await save('/office/records',{projectId,kind,title,data:payload}))close()
  }
  return <form onSubmit={submit} className="space-y-4"><Text label="Название / назначение" value={title} onChange={setTitle}/>
    {kind==='TASK'&&<>{select('assigneeId','Исполнитель',data.employees.map(u=>({id:u.id,label:u.full_name})))}<div className="grid gap-4 sm:grid-cols-2">{field('dueDate','Срок задачи','date')}{select('quadrant','Приоритет', [{id:1,label:'1 · Важное и срочное'},{id:2,label:'2 · Важное и несрочное'},{id:3,label:'3 · Срочное поручение'},{id:4,label:'4 · Пересмотреть необходимость'}])}</div><Field label="Чек-лист: каждый шаг с новой строки"><textarea rows={5} className={inputClass} value={checklist} onChange={e=>setChecklist(e.target.value)}/></Field>{textarea('improvement','Кайдзен: что улучшить и как проверить результат',false)}</>}
    {kind==='CONTRACT'&&<>{select('templateId','Утверждённый шаблон',data.templates.filter(t=>t.approved).map(t=>({id:t.id,label:t.title+' · v'+t.revision})))}{select('direction','Вид договора',[{id:'SUPPLIER',label:'С поставщиком'},{id:'CUSTOMER',label:'С заказчиком'}])}{field('counterparty','Контрагент')}{textarea('requisites','Реквизиты сторон')}{textarea('subject','Предмет договора')}{field('amount','Сумма договора, KZT')}{textarea('paymentTerms','Условия оплаты')}<div className="grid gap-4 sm:grid-cols-2">{field('startDate','Начало','date')}{field('endDate','Окончание','date')}</div></>}
    {kind==='BUDGET'&&<><p className="text-sm text-slate-600">Новая версия заменит действующий бюджет только после согласования. Лимит проверяется по общей сумме проекта.</p>{lines.map((line,i)=><div key={i} className="grid gap-2 sm:grid-cols-[1fr_160px_auto]"><Field label={`Статья ${i+1}`}><input required className={inputClass} value={line.title} onChange={e=>setLines(lines.map((l,n)=>n===i?{...l,title:e.target.value}:l))}/></Field><Field label="Сумма, KZT"><input required inputMode="decimal" className={inputClass} value={line.amount} onChange={e=>setLines(lines.map((l,n)=>n===i?{...l,amount:e.target.value}:l))}/></Field>{lines.length>1&&<button type="button" className={secondaryClass} onClick={()=>setLines(lines.filter((_,n)=>n!==i))}>Убрать</button>}</div>)}<button type="button" className={secondaryClass} onClick={()=>setLines([...lines,{title:'',amount:''}])}>Добавить статью</button></>}
    {kind==='PURCHASE'&&<>{select('contractId','Подписанный договор поставщика',contracts.filter(c=>c.direction==='SUPPLIER').map(c=>({id:c.id,label:c.code+' · '+c.counterparty})),true,id=>set('supplier',contracts.find(c=>c.id===Number(id))?.counterparty??''))}{field('supplier','Поставщик')}{field('amount','План закупки, KZT')}{field('dueDate','Нужно к дате','date')}{textarea('purpose','Что закупаем и для чего')}</>}
    {kind==='RECEIPT'&&<>{select('purchaseId','Согласованная закупка',purchases.filter(p=>p.status==='APPROVED').map(p=>({id:p.id,label:p.code+' · '+p.title})))}{field('amount','Фактически принято, KZT')}{field('date','Дата приёмки','date')}{textarea('note','Что принято, состояние и подтверждение')}</>}
    {kind==='INVOICE'&&<>{select('direction','Вид счёта',[{id:'IN',label:'Входящий — оплатить поставщику'},{id:'OUT',label:'Исходящий — получить от заказчика'}],true,()=>{set('contractId','');set('purchaseId','');setAdvance(false)})}{select('contractId','Подписанный договор',contracts.filter(c=>c.direction===(v('direction')==='IN'?'SUPPLIER':'CUSTOMER')).map(c=>({id:c.id,label:c.code+' · '+c.counterparty})),true,id=>set('counterparty',contracts.find(c=>c.id===Number(id))?.counterparty??''))}{v('direction')==='IN'&&<>{select('purchaseId','Согласованная закупка',purchases.filter(p=>p.data.contractId===Number(v('contractId'))).map(p=>({id:p.id,label:p.code+' · '+p.title})))}{field('externalNumber','Номер счёта поставщика')}</>}{field('counterparty','Контрагент')}{field('amount','Сумма счёта, KZT')}{textarea('requisites','Реквизиты для оплаты')}<div className="grid gap-4 sm:grid-cols-2">{field('issueDate','Дата счёта','date')}{field('dueDate','Оплатить до','date')}</div>{v('direction')==='IN'&&<><label className="flex gap-2"><input type="checkbox" checked={advance} onChange={e=>setAdvance(e.target.checked)}/>Аванс до приёмки</label>{advance&&textarea('advanceReason','Основание аванса в договоре')}</>}</>}
    {kind==='PAYMENT'&&<><p className="rounded-lg bg-amber-50 p-3 text-sm">Здесь учитывается уже подтверждённая оплата. Перевод денег в банке эта кнопка не выполняет.</p>{select('invoiceId','Согласованный счёт',invoices.map(p=>({id:p.id,label:p.code+' · '+p.title})))}{field('amount','Сумма подтверждённой оплаты, KZT')}{field('date','Дата оплаты','date')}{field('reference','Номер платёжного документа')}</>}
    <div className="flex gap-3"><button disabled={busy} className={buttonClass}>Сохранить запись</button><button type="button" onClick={close} className={secondaryClass}>Закрыть</button></div>
  </form>
}
