import { useCallback, useEffect, useRef, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { apiDownload, apiRequest, toUserMessage } from '@/api/client'
import { AccountControls } from '@/components/AccountControls'
import { useAuth } from '@/context/AuthContext'
import { getToken } from '@/lib/auth'
import { canPerform } from '@/lib/accessPolicy'
import { ProjectEditor, RecordEditor, TemplateEditor } from './OfficeForms'
import { Panel, inputClass, buttonClass, secondaryClass, moneyLabel, scopeNames, kindNames, statusNames, createRights, type OfficeRow, type Workspace } from './office-ui'

type Save=(path:string,body:Record<string,unknown>)=>Promise<boolean>
function RecordCard({row,data,busy,save,upload,download,userId}:{row:OfficeRow;data:Workspace;busy:boolean;save:Save;upload:(id:number,file:File)=>Promise<void>;download:(path:string,name:string)=>Promise<void>;userId:number}){
  const {user}=useAuth();const rights=data.access.rights,can=(r:string)=>rights.includes(r),allowed=canPerform(user,'office.recordAction')
  const [note,setNote]=useState(''),[checks,setChecks]=useState<boolean[]>((row.data.checklist??[]).map((s:any)=>s.done))
  const action=(code:string)=>void save('/office/actions',{id:row.id,revision:row.revision,action:code,note,...(code==='CHECK'?{checked:checks}:{})})
  const isTask=row.kind==='TASK',own=row.assignee_id===userId||data.access.profile==='EXECUTIVE',draft=row.status==='DRAFT',submitted=row.status==='SUBMITTED',active=data.projects.find(p=>p.id===row.project_id)?.status==='ACTIVE'
  const actions:{code:string;label:string}[]=[]
  if(active&&allowed){
    if(isTask){
      if(can('work')&&own&&['TODO','IN_PROGRESS','REWORK'].includes(row.status))actions.push({code:'CHECK',label:'Сохранить шаги'},{code:'SUBMIT',label:'Передать на приёмку'})
      if(can('quality')&&submitted&&(row.assignee_id!==userId||data.access.profile==='EXECUTIVE'))actions.push({code:'ACCEPT',label:'Принять результат'},{code:'REWORK',label:'Вернуть на доработку'})
      if(can('plan')&&!['DONE','CANCELLED'].includes(row.status))actions.push({code:'CANCEL',label:'Отменить задачу'})
    }else{
      if(draft&&can(createRights[row.kind])&&['CONTRACT','BUDGET','PURCHASE','INVOICE'].includes(row.kind))actions.push({code:'SUBMIT',label:'На согласование'})
      if(submitted&&can(row.kind==='CONTRACT'?'sign':'approve'))actions.push({code:row.kind==='CONTRACT'?'SIGN':'APPROVE',label:row.kind==='CONTRACT'?'Зарегистрировать подписание':'Согласовать'},{code:'REJECT',label:'Вернуть с замечанием'})
      if(['CONTRACT','BUDGET','PURCHASE','INVOICE'].includes(row.kind)&&can(createRights[row.kind])&&(['DRAFT','SUBMITTED'].includes(row.status)||data.access.profile==='EXECUTIVE'&&['SIGNED','APPROVED'].includes(row.status)&&row.kind!=='BUDGET'))actions.push({code:'CANCEL',label:'Отменить документ'})
    }
  }
  if(allowed&&can('reverse')&&['PAYMENT','RECEIPT'].includes(row.kind)&&row.status==='RECORDED')actions.push({code:'VOID',label:'Сторнировать запись'})
  const paid=Number(row.paid_amount??0)
  const overdue=row.due_date&&row.due_date<data.today&&!['DONE','CANCELLED','VOID','PAID','RECEIVED','SUPERSEDED'].includes(row.status)
  return <article className="min-w-0 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm">
    <div className="flex flex-wrap items-start justify-between gap-2"><div className="min-w-0"><p className="text-xs font-semibold tracking-wide text-slate-500">{row.code} · версия {row.revision}</p><h3 className="mt-1 break-words text-lg font-bold">{row.title}</h3></div><span className={`rounded-lg px-2 py-1 text-xs font-semibold ${row.status==='DONE'||row.status==='PAID'?'bg-emerald-50 text-emerald-800':'bg-slate-100 text-slate-700'}`}>{isTask&&submitted?'На приёмке':statusNames[row.status]??row.status}</span></div>
    {isTask?<p className="my-2 text-sm">Исполнитель: {row.assignee_name??'Не назначен'} · Квадрат {row.data.quadrant}{row.data.quadrant==='2'?' · Важное и несрочное':''}</p>:<p className="my-2 text-xl font-bold">{moneyLabel(row.amount)}</p>}
    {row.due_date&&<p className={`text-sm ${overdue?'font-semibold text-red-700':'text-slate-600'}`}>{row.kind==='INVOICE'?'Оплатить до':'Срок'}: {row.due_date}{overdue?' · Срок прошёл':''}</p>}
    {row.kind==='INVOICE'&&<p className="my-2 text-sm">{row.data.direction==='IN'?'Оплата поставщику':'Поступление от заказчика'} · Учтено {moneyLabel(paid)} · Остаток {moneyLabel(Number(row.amount)-paid)}{row.data.advance?' · Аванс':''}</p>}
    {row.data.counterparty&&<p className="mt-2 text-sm">Контрагент: {row.data.counterparty}</p>}{row.data.supplier&&<p className="mt-2 text-sm">Поставщик: {row.data.supplier}</p>}
    {row.parent_id&&<p className="mt-2 text-sm text-slate-600">Основание: {data.records.find(r=>r.id===row.parent_id)?.code??`№ ${row.parent_id}`}</p>}
    {row.data.contractId&&<p className="mt-2 text-sm text-slate-600">Договор: {data.records.find(r=>r.id===row.data.contractId)?.code??data.contractOptions.find(c=>c.id===row.data.contractId)?.code??`№ ${row.data.contractId}`}</p>}
    {row.data.checklist&&<ul className="my-3 space-y-2">{row.data.checklist.map((s:any,i:number)=><li key={i}><label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={checks[i]} disabled={busy||!active||!own||!can('work')||!allowed||!['TODO','IN_PROGRESS','REWORK'].includes(row.status)} onChange={e=>setChecks(checks.map((v,n)=>n===i?e.target.checked:v))}/>{s.text}</label></li>)}</ul>}
    {row.data.improvement&&<div className="my-3 rounded-lg bg-purple-50 p-3 text-sm"><strong>Кайдзен — ожидаемый результат</strong><p className="whitespace-pre-wrap">{row.data.improvement}</p></div>}
    {row.data.lines&&<ul className="my-3 space-y-1 text-sm">{row.data.lines.map((l:any,i:number)=><li key={i} className="flex justify-between gap-3"><span>{l.title}</span><strong>{moneyLabel(l.amount)}</strong></li>)}</ul>}
    {(['subject','paymentTerms','purpose','note','result','review','rejection','approvalNote','advanceReason','cancellation','voidReason','reference'] as const).filter(k=>row.data[k]).map(k=><p key={k} className="mt-2 whitespace-pre-wrap break-words text-sm text-slate-700"><strong>{{subject:'Предмет',paymentTerms:'Условия оплаты',purpose:'Основание',note:'Комментарий',result:'Результат',review:'Проверка',rejection:'Замечание',approvalNote:'Согласование',advanceReason:'Основание аванса',cancellation:'Причина отмены',voidReason:'Причина сторно',reference:'Платёжный документ'}[k]}:</strong> {row.data[k]}</p>)}
    {['CONTRACT','INVOICE'].includes(row.kind)&&<div className="mt-3 space-y-2 border-t pt-3">
      {canPerform(user,'office.print')&&<button className={secondaryClass} onClick={()=>void download(`/office/records/${row.id}/print`,`${row.code}.html`)}>Скачать печатную форму</button>}
      {data.documents.filter(d=>d.record_id===row.id).map(d=><div key={d.id}>{canPerform(user,'office.download')&&<button className="break-all text-left text-sm text-blue-700 underline" onClick={()=>void download(`/office/documents/${d.id}`,d.name)}>{d.name}</button>}</div>)}
      {active&&can(row.kind==='CONTRACT'?'contract':'invoice')&&canPerform(user,'office.upload')&&['DRAFT','SUBMITTED'].includes(row.status)&&<label className="block text-sm font-semibold">Прикрепить {row.kind==='CONTRACT'?'подписанный договор':'счёт поставщика'} (PDF, JPEG, PNG до 10 МБ)<input className="mt-2 block max-w-full text-sm" type="file" disabled={busy} accept="application/pdf,image/png,image/jpeg" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(row.id,file);e.target.value=''}}/></label>}
    </div>}
    {actions.length>0&&<div className="mt-4 space-y-3 border-t pt-3"><label className="block text-sm font-medium">Комментарий / результат<textarea disabled={busy} className={'mt-1 '+inputClass} rows={2} value={note} onChange={e=>setNote(e.target.value)}/></label><div className="flex flex-wrap gap-2">{actions.map(a=><button key={a.code} disabled={busy} onClick={()=>action(a.code)} className={a.code==='ACCEPT'||a.code==='APPROVE'?buttonClass:secondaryClass}>{a.label}</button>)}</div></div>}
  </article>
}
export function OfficePage(){
  const {user}=useAuth();const [params,setParams]=useSearchParams();const projectId=Number(params.get('project'))||undefined
  const [data,setData]=useState<Workspace|null>(null),[error,setError]=useState(''),[success,setSuccess]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[editor,setEditor]=useState<string|null>(null),[search,setSearch]=useState(''),[focus,setFocus]=useState('all')
  const requestRevision=useRef(0),lock=useRef(false),retry=useRef<{body:string;id:string}|null>(null)
  const load=useCallback(async()=>{const rev=++requestRevision.current,token=getToken();setLoading(true);setError('');try{const result=await apiRequest<Workspace>(`/office/workspace${projectId?'?projectId='+projectId:''}`);if(rev===requestRevision.current&&token===getToken())setData(result)}catch(e){if(rev===requestRevision.current&&token===getToken()){setData(null);setError(toUserMessage(e))}}finally{if(rev===requestRevision.current)setLoading(false)}},[user?.id,projectId])
  useEffect(()=>{setData(null);setEditor(null);void load();return()=>{++requestRevision.current}},[load])
  useEffect(()=>{const refresh=()=>{if(!lock.current)void load()};window.addEventListener('focus',refresh);return()=>window.removeEventListener('focus',refresh)},[load])
  const save:Save=async(path,body)=>{if(lock.current)return false;lock.current=true;setBusy(true);setError('');setSuccess('');const token=getToken(),serialized=JSON.stringify({path,body});if(retry.current?.body!==serialized)retry.current={body:serialized,id:crypto.randomUUID()};try{
    await apiRequest(path,{method:'POST',body:JSON.stringify({...body,requestId:retry.current.id})});if(token!==getToken())return false;retry.current=null;setSuccess('Сохранено на сервере.');await load();return true
  }catch(e){if(token===getToken())setError(toUserMessage(e));return false}finally{lock.current=false;setBusy(false)}}
  async function upload(id:number,file:File){if(lock.current)return;lock.current=true;setBusy(true);setError('');const token=getToken();try{const form=new FormData();form.append('file',file);await apiRequest(`/office/records/${id}/documents`,{method:'POST',body:form});if(token!==getToken())return;setSuccess('Документ прикреплён.');await load()}catch(e){if(token===getToken())setError(toUserMessage(e))}finally{lock.current=false;setBusy(false)}}
  async function download(path:string,name:string){setError('');const token=getToken();try{const blob=await apiDownload(path);if(token!==getToken())return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){if(token===getToken())setError(toUserMessage(e))}}
  const tab=params.get('tab')??'TASK',views=data?.access.views??[],kind=views.includes(tab)?tab:views[0],project=data?.projects.find(p=>p.id===projectId)
  const records=(data?.records??[]).filter(r=>r.kind===kind&&(!search||(r.code+' '+r.title+' '+(r.data.counterparty??'')).toLowerCase().includes(search.toLowerCase()))&&(focus==='all'||focus==='q2'&&r.kind==='TASK'&&r.data.quadrant==='2'||focus==='pending'&&r.status==='SUBMITTED'||focus==='overdue'&&r.due_date&&r.due_date<data!.today&&!['DONE','CANCELLED','VOID','PAID','RECEIVED','SUPERSEDED'].includes(r.status)))
  function chooseProject(value:string){setParams(value?{project:value,tab:kind??'TASK'}:{tab:kind??'TASK'});setEditor(null)}
  const can=(right:string)=>data?.access.rights.includes(right),executive=data?.access.profile==='EXECUTIVE'
  const budget=data?.financial?.budget,committed=Number(data?.financial?.committed??0)
  return <div className="min-h-dvh bg-slate-50 text-slate-900"><header className="border-b bg-white px-4 py-4"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4"><Link to="/office" className="text-xl font-black"><span className="text-emerald-700">GP</span> Work</Link><AccountControls/></div></header>
    <main className="mx-auto max-w-7xl space-y-5 p-4 md:p-6">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-3xl font-bold">Мой рабочий кабинет</h1>{data&&<p className="mt-2 text-slate-600">{data.access.label}{data.access.unitName?' · '+data.access.unitName:''}<br/><span className="text-sm">{scopeNames[data.access.scope]}</span></p>}</div><nav className="flex flex-wrap gap-2"><Link className={secondaryClass} to="/my-work-day">Мой рабочий день</Link>{executive&&<><Link className={secondaryClass} to="/admin/organization">Структура и состав</Link><Link className={secondaryClass} to="/admin/office-access">Личные доступы</Link><Link className={secondaryClass} to="/admin">Общий кабинет</Link></>}<button className={secondaryClass} disabled={loading||busy} onClick={()=>void load()}>Обновить</button></nav></div>
      {error&&<p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-800">{error}</p>}{success&&<p role="status" className="rounded-xl bg-emerald-50 p-3 text-emerald-900">{success}</p>}
      {loading&&!data&&<p>Загрузка рабочего кабинета…</p>}
      {data&&<><section className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex flex-wrap items-end gap-3"><label className="min-w-0 flex-1 text-sm font-semibold">Проект<select className={'mt-1 '+inputClass} value={projectId??''} onChange={e=>chooseProject(e.target.value)}><option value="">Все доступные проекты</option>{data.projects.map(p=><option key={p.id} value={p.id}>{p.code} · {p.title}</option>)}</select></label>{can('project')&&canPerform(user,'office.projectSave')&&<button className={buttonClass} onClick={()=>setEditor('project-new')}>Новый проект</button>}{project&&can('project')&&canPerform(user,'office.projectSave')&&(executive||project.owner_id===user!.id)&&<button className={secondaryClass} onClick={()=>setEditor('project-edit')}>План и состав проекта</button>}</div>
        {project&&<div className="mt-3 space-y-1 text-sm text-slate-600"><p>{project.unit_name} · Ответственный: {project.owner_name}</p><p>{project.start_date} — {project.due_date} · {statusNames[project.status]}</p><p className="whitespace-pre-wrap">{project.description}</p></div>}
        {!data.projects.length&&<p className="mt-4 rounded-lg bg-slate-50 p-3">Пока нет доступных проектов. {can('project')?'Создайте проект и добавьте подразделения и участников.':'Руководитель должен добавить вас или ваше подразделение в проект.'}</p>}
      </section>
      {editor?.startsWith('project-')&&<Panel title={editor==='project-edit'?'План и состав проекта':'Новый проект'}><ProjectEditor key={editor+String(projectId)} data={data} existing={editor==='project-edit'?project:undefined} busy={busy} save={save} close={()=>setEditor(null)} userId={user!.id}/></Panel>}
      {projectId&&data.access.views.includes('BUDGET')&&<div className="grid gap-3 sm:grid-cols-3">{[['Утверждённый бюджет',budget?moneyLabel(budget):'Не утверждён'],['Согласованные закупки',moneyLabel(committed)],['Свободный лимит',budget?moneyLabel(Number(budget)-committed):'—']].map(([label,value])=><div key={label} className="rounded-xl border bg-white p-4"><p className="text-sm text-slate-500">{label}</p><strong className="text-xl">{value}</strong></div>)}</div>}
      <nav aria-label="Разделы рабочего кабинета" className="flex flex-wrap gap-2">{views.map(k=><button key={k} className={kind===k?buttonClass:secondaryClass} onClick={()=>{setParams({...Object.fromEntries(params),tab:k});setEditor(null);setFocus('all')}}>{kindNames[k]}</button>)}{can('template')&&canPerform(user,'office.templateSave')&&<button className={editor==='templates'?buttonClass:secondaryClass} onClick={()=>setEditor(editor==='templates'?null:'templates')}>Шаблоны договоров</button>}</nav>
      {editor==='templates'&&<Panel title="Шаблоны и версии договоров"><TemplateEditor data={data} busy={busy} save={save}/></Panel>}
      <div className="flex flex-wrap items-end gap-3"><label className="min-w-0 flex-1 text-sm font-semibold">Поиск по доступным записям<input className={'mt-1 '+inputClass} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Номер, название, контрагент"/></label><label className="text-sm font-semibold">Показать<select className={'mt-1 '+inputClass} value={focus} onChange={e=>setFocus(e.target.value)}><option value="all">Все</option>{kind==='TASK'&&<option value="q2">Квадрат 2 · развитие и профилактика</option>}<option value="pending">Ожидают проверки</option><option value="overdue">Срок прошёл</option></select></label>{project?.status==='ACTIVE'&&can(createRights[kind])&&canPerform(user,'office.recordCreate')&&<button className={buttonClass} onClick={()=>setEditor(kind)}>Добавить запись</button>}</div>
      {!projectId&&can(createRights[kind])&&<p className="text-sm text-slate-600">Для создания записи выберите проект.</p>}
      {editor===kind&&projectId&&<Panel title={'Новая запись · '+kindNames[kind]}><RecordEditor key={kind+projectId} kind={kind} projectId={projectId} data={data} busy={busy} save={save} close={()=>setEditor(null)}/></Panel>}
      {data.records.length>=data.limits.records&&<p className="rounded-lg bg-amber-50 p-3">Показаны последние {data.limits.records} записи. Уточните проект. Финансовые итоги рассчитаны сервером по всем его записям.</p>}
      <section aria-label={kindNames[kind]} className="grid items-start gap-4 lg:grid-cols-2">{records.map(r=><RecordCard key={r.id+':'+r.revision} row={r} data={data} busy={busy||loading} save={save} upload={upload} download={download} userId={user!.id}/>)}{!records.length&&<p className="rounded-xl border border-dashed bg-white p-5 text-slate-600">В этом разделе пока нет доступных записей{focus!=='all'?' с выбранным фильтром':''}.</p>}</section>
      {projectId&&<details className="rounded-xl border bg-white p-4"><summary className="cursor-pointer font-bold">История проекта</summary><ul className="mt-3 space-y-2 text-sm">{data.events.map(e=><li key={e.id}>{new Date(e.created_at).toLocaleString('ru-RU')} · {e.actor_name} · {kindNames[e.category]??'Проект'} · {statusNames[e.action]??e.action}</li>)}</ul>{!data.events.length&&<p className="mt-2 text-sm">Нет доступных событий.</p>}</details>}
      </>}
    </main></div>
}
