import { useRef,useState } from 'react'
import { useAuth } from '@/context/AuthContext'
import { ApiError,toUserMessage } from '@/api/client'
import { CATEGORIES,OBSTACLE_STATUS,IMPROVEMENT_STATUS,workflowPost,type Obstacle,type Improvement,type Person } from '@/api/workflowApi'
import { Label,inputClass,buttonClass,panelClass } from './Controls'
export function ReportForm({taskId,obstacles,onChanged}:{taskId:number;obstacles:Obstacle[];onChanged:()=>Promise<void>}) {
  const [kind,setKind]=useState('obstacle');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [retry,setRetry]=useState(false)
  const pending=useRef<{path:string;body:unknown}|null>(null)
  async function submit(e:React.FormEvent<HTMLFormElement>) {e.preventDefault();if(busy)return;const form=e.currentTarget;const d=new FormData(form);setBusy(true);setError('');try {
    if(!pending.current) pending.current={path:`/tasks/${taskId}/${kind==='obstacle'?'obstacles':'improvements'}`,body:kind==='obstacle'?{category:d.get('category'),description:d.get('description'),clientOperationId:crypto.randomUUID()}:{problem:d.get('description'),proposal:d.get('proposal'),...(d.get('obstacleId')?{obstacleId:Number(d.get('obstacleId'))}:{}),clientOperationId:crypto.randomUUID()}}
    await workflowPost(pending.current.path,pending.current.body);pending.current=null;setRetry(false);form.reset();await onChanged()
  }catch(err){if(err instanceof ApiError && err.status && err.status<500) pending.current=null;setRetry(!!pending.current);setError(toUserMessage(err))}finally{setBusy(false)}}
  return <section className={panelClass}><h2 className="text-lg font-bold">Помощь и предложения</h2><form onSubmit={submit} className="space-y-3"><fieldset disabled={busy||retry} className="space-y-3"><Label name="Что хотите сообщить"><select className={inputClass} value={kind} onChange={e=>setKind(e.target.value)}><option value="obstacle">Есть препятствие</option><option value="improvement">Предложить улучшение</option></select></Label>
    {kind==='obstacle'?<Label name="Что мешает"><select className={inputClass} name="category">{Object.entries(CATEGORIES).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></Label>:<Label name="Связанное препятствие"><select className={inputClass} name="obstacleId" defaultValue=""><option value="">Без привязки</option>{obstacles.map(o=><option key={o.id} value={o.id}>#{o.id} · {o.description.slice(0,80)}</option>)}</select></Label>}
    <Label name="Что произошло"><textarea className={inputClass} name="description" required maxLength={2000} rows={3}/></Label>{kind==='improvement'&&<Label name="Что предлагаете изменить"><textarea className={inputClass} name="proposal" required maxLength={2000} rows={3}/></Label>}</fieldset>
    <button type="submit" className={buttonClass} disabled={busy}>{busy?'Сохраняем…':retry?'Повторить отправку':kind==='obstacle'?'Сообщить о препятствии':'Отправить предложение'}</button>
    {retry&&<p className="text-sm">Повтор отправит то же сообщение с защитой от дублирования.</p>}{error&&<p role="alert" className="text-red-700">{error}</p>}
  </form></section>
}
export function ObstacleCard({item,people,canManage,onChanged}:{item:Obstacle;people:Person[];canManage:boolean;onChanged:()=>Promise<void>}) {
  const {user}=useAuth();const open=['OPEN','WORKING'].includes(item.status);const actions=[...(canManage&&open?['assign']:[]),...((canManage||item.owner_id===user!.id)&&open?['resolve']:[]),...((canManage||item.reporter_id===user!.id)&&item.status==='RESOLVED'?[...(item.resolved_by_id!==user!.id?['verify']:[]),'reopen']:[])]
  const labels:Record<string,string>={assign:'Назначить ответственного и срок',resolve:'Устранено — передать на проверку',verify:'Подтвердить устранение',reopen:'Проблема осталась'}
  const [action,setAction]=useState(actions[0]??'');const [busy,setBusy]=useState(false);const [error,setError]=useState('')
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);setBusy(true);setError('');try{await workflowPost(`/obstacles/${item.id}/actions`,{action,note:d.get('note'),...(action==='assign'?{ownerId:Number(d.get('ownerId')),dueAt:new Date(String(d.get('dueAt'))).toISOString()}:{})});await onChanged()}catch(err){setError(toUserMessage(err))}finally{setBusy(false)}}
  return <article className={panelClass}><h3 className="font-bold">#{item.id} · {CATEGORIES[item.category]} · {OBSTACLE_STATUS[item.status]}</h3><p>{item.description}</p><p className="text-sm">Сообщил: {item.reporter_name}. Ответственный: {item.owner_name}{item.due_at?` · срок ${new Date(item.due_at).toLocaleString('ru-RU')}`:' · срок ещё не назначен'}</p>{item.resolution&&<p><b>Что сделали:</b> {item.resolution}</p>}{item.verification&&<p><b>Проверка:</b> {item.verification}</p>}
    {!!actions.length&&<form onSubmit={submit} className="space-y-3"><fieldset disabled={busy} className="space-y-3"><Label name="Действие по препятствию"><select className={inputClass} value={action} onChange={e=>setAction(e.target.value)}>{actions.map(a=><option key={a} value={a}>{labels[a]}</option>)}</select></Label>{action==='assign'&&<><Label name="Ответственный за устранение"><select className={inputClass} name="ownerId" required defaultValue={item.owner_id}>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Label><Label name="Срок устранения"><input type="datetime-local" name="dueAt" className={inputClass} required/></Label></>}<Label name="Что сделано или проверено"><textarea name="note" className={inputClass} required maxLength={2000}/></Label><button className={buttonClass} type="submit">{labels[action]}</button></fieldset>{error&&<p role="alert" className="text-red-700">{error}</p>}</form>}
  </article>
}
export function ImprovementCard({item,people,canManage,canAdopt,onChanged}:{item:Improvement;people:Person[];canManage:boolean;canAdopt:boolean;onChanged:()=>Promise<void>}) {
  const {user}=useAuth();const actions=[...(canManage&&item.status==='PROPOSED'?['plan']:[]),...((canManage||item.owner_id===user!.id)&&item.status==='TESTING'?['measure']:[]),...(canAdopt&&item.owner_id!==user!.id&&item.status==='CHECKING'?['adopt']:[]),...(canManage&&!['ADOPTED','REJECTED'].includes(item.status)?['reject']:[])]
  const labels:Record<string,string>={plan:'Начать проверку предложения',measure:'Отправить измеренный результат',adopt:'Утвердить новое правило',reject:'Отклонить с объяснением'}
  const [action,setAction]=useState(actions[0]??'');const [error,setError]=useState('');const [busy,setBusy]=useState(false)
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);setBusy(true);setError('');try {await workflowPost(`/improvements/${item.id}/actions`,{action,note:d.get('note'),...(action==='plan'?{ownerId:Number(d.get('ownerId')),dueAt:new Date(String(d.get('dueAt'))).toISOString(),hypothesis:d.get('hypothesis'),metric:d.get('metric'),unit:d.get('unit'),direction:d.get('direction'),baseline:Number(d.get('baseline'))}:action==='measure'?{observed:Number(d.get('observed'))}:action==='adopt'?{adoptionRule:d.get('adoptionRule')}:{})});await onChanged()}catch(err){setError(toUserMessage(err))}finally{setBusy(false)}}
  return <article className={panelClass}><h3 className="font-bold">Предложение #{item.id} · {IMPROVEMENT_STATUS[item.status]}</h3><p><b>Проблема:</b> {item.problem}</p><p><b>Предложение:</b> {item.proposal}</p><p className="text-sm">Автор: {item.proposer_name}{item.owner_name?` · проверяет ${item.owner_name}`:''}{item.due_at?` · срок ${new Date(item.due_at).toLocaleString('ru-RU')}`:''}</p>{item.hypothesis&&<p><b>Гипотеза причины:</b> {item.hypothesis}</p>}{item.metric&&<p><b>{item.metric}:</b> было {item.baseline??'не измерено'} {item.unit}, после {item.observed??'не измерено'} {item.unit}</p>}{item.evidence&&<p><b>Доказательства:</b> {item.evidence}</p>}{item.decision&&<p><b>Решение:</b> {item.decision}</p>}{item.adopted_standard_id&&<p className="text-emerald-700">Создана новая версия стандарта. Текущая задача сохраняет свою инструкцию.</p>}
    {!!actions.length&&<details><summary className="cursor-pointer font-semibold text-blue-700">Следующий шаг</summary><form onSubmit={submit} className="mt-3 space-y-3"><fieldset disabled={busy} className="space-y-3"><Label name="Действие по улучшению"><select className={inputClass} value={action} onChange={e=>setAction(e.target.value)}>{actions.map(a=><option key={a} value={a}>{labels[a]}</option>)}</select></Label>
    {action==='plan'&&<><Label name="Кто проверяет изменение"><select className={inputClass} name="ownerId" required defaultValue=""><option value="">Выберите сотрудника</option>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Label><Label name="Срок проверки"><input type="datetime-local" name="dueAt" className={inputClass} required/></Label><Label name="Предполагаемая причина"><textarea name="hypothesis" className={inputClass} maxLength={2000} required/></Label><Label name="Что измеряем"><input name="metric" className={inputClass} placeholder="Например: ожидание воды за смену" maxLength={200} required/></Label><Label name="Единица измерения"><input name="unit" className={inputClass} placeholder="мин, м², тг" maxLength={40} required/></Label><Label name="Что считается улучшением"><select name="direction" className={inputClass}><option value="LOWER">Значение уменьшается</option><option value="HIGHER">Значение увеличивается</option></select></Label><Label name="Измеренное значение до изменения"><input type="number" step="any" name="baseline" className={inputClass} required/></Label></>}
    {action==='measure'&&<Label name="Измеренное значение после изменения"><input type="number" step="any" name="observed" className={inputClass} required/></Label>}
    {action==='adopt'&&<Label name="Новое правило для инструкции"><textarea name="adoptionRule" className={inputClass} maxLength={300} required/></Label>}
    <Label name={action==='measure'?'Где и как измеряли результат':'Обоснование решения'}><textarea name="note" className={inputClass} maxLength={2000} required/></Label><button type="submit" className={buttonClass}>{labels[action]}</button></fieldset>{error&&<p role="alert" className="text-red-700">{error}</p>}</form></details>}
  </article>
}
