import { apiRequest } from './client'
export const workflowGet = <T,>(path:string) => apiRequest<T>(`/workflow${path}`)
export const workflowPost = <T,>(path:string,body:unknown) => apiRequest<T>(`/workflow${path}`,{method:'POST',body:JSON.stringify(body)})
export const STAGES: Record<string,string> = {PLANNED:'Подготовить',READY:'Готово к работе',WORKING:'В работе',BLOCKED:'Есть препятствие',REVIEW:'На приёмке',REWORK:'На доработке',DONE:'Принято',CANCELLED:'Отменено'}
export const CATEGORIES: Record<string,string> = {WATER:'Вода',MATERIAL:'Материалы',TOOL:'Инструмент',ACCESS:'Доступ на участок',APP:'Приложение',OTHER:'Другое'}
export const OBSTACLE_STATUS: Record<string,string> = {OPEN:'Нужна помощь',WORKING:'Устраняют',RESOLVED:'Проверьте результат',CLOSED:'Устранено и проверено'}
export const IMPROVEMENT_STATUS: Record<string,string> = {PROPOSED:'Предложено',TESTING:'Проверяем изменение',CHECKING:'Результат на проверке',ADOPTED:'Включено в стандарт',REJECTED:'Не принято'}
export type Standard = {id:number;work_type_id:number;version:number;title:string;steps:string[];preparation:string[];acceptance:string;work_type_name?:string}
export type Person = {id:number;name:string;role:string}
export type Catalog = {standards:Standard[];workTypes:{id:number;name:string}[];people:Person[];products:{id:number;name:string;unit:string|null}[]}
export type BoardTask = {id:number;description:string;objectName:string;sectionName:string;stage:string;status:string;obstacleCount:number;assigneeName:string;accountableName:string|null;reviewerName:string|null;executionId:number|null;configured:boolean}
export type ToolItem = {id:number;code:string;name:string;home_location:string;current_location:string;state:'READY'|'ISSUED'|'MAINTENANCE'|'RETIRED';task_id:number|null;condition_note:string;checked_at:string|null}
export type Obstacle = {id:number;reporter_id:number;owner_id:number;reporter_name:string;owner_name:string;category:string;description:string;status:string;resolution:string|null;verification:string|null;resolved_by_id:number|null;due_at:string|null;created_at:string}
export type Improvement = {id:number;status:string;problem:string;proposal:string;proposer_name:string;owner_id:number|null;owner_name:string|null;hypothesis:string|null;metric:string|null;unit:string|null;baseline:number|null;observed:number|null;direction:string|null;evidence:string|null;decision:string|null;due_at:string|null;adopted_standard_id:number|null}
export type TaskFlow = {task:{id:number;description:string;section_name:string;section_code:string;section_id:number;object_id:number;object_name:string;work_type_id:number;work_type_name?:string;status:string;assignee_user_id:number;assignee_name:string};plan:(Standard&{standard_id:number;accountable_id:number;reviewer_id:number;wip_limit:number;required_tool_ids:number[];materials:{productId:number;quantity:number}[];ready_at:string|null;checked_preparation:number[];completed_steps:number[];accountable_name:string;reviewer_name:string})|null;obstacles:Obstacle[];improvements:Improvement[];tools:ToolItem[];readiness:string[];canManage:boolean;canExecute:boolean;canAdopt:boolean;execution:{id:number;status:string}|null;events:{id:number;kind:string;actor_name:string;created_at:string}[];materials:{productId:number;name:string;required:number;issued:number;missing:number}[]}
export type Summary = {periodDays:number;counts?:Record<string,number>;waitingByCategory?:{category:string;minutes:number}[];overdueObstacles?:number;interpretation?:string;improvements?:{id:number;status:string;metric:string|null;unit:string|null;baseline:number|null;observed:number|null}[];financial?:{id:number;metric:string;unit:string;baseline:number;observed:number;status:string;evidence:string|null;decision:string|null}[]}
