import { loadEnvFiles } from './load-env';
import { DataSource } from 'typeorm';
import { getTypeOrmPostgresOptions } from './database.config';
import {
  AdminDailyReport,
  ScheduleEntry,
  ManagementDecision,
  Brigade,
  BrigadeMember,
  FormSetting,
  NurseryObject,
  Section,
  SectionCodeCounter,
  Task,
  User,
  WateringRecord,
  WorkLog,
  WorkType,
  Route,
  RouteStop,
  WorkExecution,
  WorkExecutionEvent,
  WorkPhoto,
  ChecklistItem,
  ChecklistAnswer,
  FaceVerification,
  LocationEvent,
  SyncOperation,
  Product,
  StockMovement,
  AttendanceRecord,
  AiAgronomAnalysis,
  Vehicle,
  VehicleAssignment,
  NurseryBatch,
  NurseryMovement,
} from '../entities';

loadEnvFiles();

export default new DataSource({
  ...getTypeOrmPostgresOptions(),
  entities: [
    NurseryObject,
    Section,
    WorkType,
    WorkLog,
    SectionCodeCounter,
    User,
    Brigade,
    BrigadeMember,
    Task,
    FormSetting,
    WateringRecord,
    AdminDailyReport,
    ScheduleEntry,
    ManagementDecision,
    Route,
    RouteStop,
    WorkExecution,
    WorkExecutionEvent,
    WorkPhoto,
    ChecklistItem,
    ChecklistAnswer,
    FaceVerification,
    LocationEvent,
    SyncOperation,
    Product,
    StockMovement,
    AttendanceRecord,
    AiAgronomAnalysis,
    Vehicle,
    VehicleAssignment,
    NurseryBatch,
    NurseryMovement,
  ],
  migrations: [__dirname + '/migrations/*{.ts,.js}'],
});
